# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Pre-release and Prepare next development version

# This workflow is triggered manually to release current version and prepare for next one
# It also creates a Pre-Release on GitHub

on: workflow_dispatch

jobs:
  call-prepare-next-dev-workflow:
    name: Prepare next development version
    uses: riseclipse/riseclipse-developer/.github/workflows/Shared-Prepare-Next-Dev-Tools.yml@master
    with:
      jarPath1: riseclipse-validator-cgmes-3-0-0/fr.centralesupelec.edf.riseclipse.cim.cgmes-v3_0_0.validator/target/RiseClipseValidatorCGMES3.jar
      jarPath2: riseclipse-validator-cgmes-3-0-0/fr.centralesupelec.edf.riseclipse.cim.cgmes-v3_0_0.validator.ui/target/RiseClipseValidatorCGMES3Application.jar
      toolSourcePath: fr.centralesupelec.edf.riseclipse.cim.cgmes-v3_0_0.validator/src/fr/centralesupelec/edf/riseclipse/cim/cgmes_v3_0_0/validator/RiseClipseValidatorCGMES.java

  call-create-pre-release-workflow:
    needs: [call-prepare-next-dev-workflow]
    name: Create Pre-Release on GitHub
    uses: riseclipse/riseclipse-developer/.github/workflows/Shared-Pre-Release-GH.yml@master
    with:
      release_version: ${{ needs.call-prepare-next-dev-workflow.outputs.release_version }}
